#!/usr/bin/env python3
"""Generate test_paged_attention_ref.py."""
import os

lines = []
L = lines.append

def W():
    path = "/mnt/e/mini-vllm-continuous-batching-lab/tests/test_paged_attention_ref.py"
    with open(path, "w") as f:
        f.write("\n".join(lines))
        f.write("\n")
    print(f"Wrote {len(lines)} lines to {path}")

L('"""Tests for Milestone A: PagedAttention Correctness.')
L('')
L('Covers ``gather_paged_kv``, ``AttentionBackendRef`` decode/prefill')
L('attention, GQA, offset-aware causal mask, scale, and SDPA tensor layout.')
L('"""')
L('')
L('from __future__ import annotations')
L('')
L('import pytest')
L('import torch')
L('import torch.nn.functional as F')
L('')
L('from mini_vllm.cache.cache_read import gather_paged_kv')
L('from mini_vllm.cache.cache_write import write_to_paged_cache')
L('from mini_vllm.attention.paged_attention_ref import AttentionBackendRef')
L('from mini_vllm.model_runner.base import (')
L('    ModelConfig, AttentionMetadata, AttentionGroup,')
L(')')
L('from mini_vllm.attention.backend import AttentionBackend as AttentionBackendFactory')
L('')
L('')
L('# ---------------------------------------------------------------------------')
L('# Constants  (defaults for most tests)')
L('# ---------------------------------------------------------------------------')
L('')
L('NUM_BLOCKS = 32')
L('BLOCK_SIZE = 4')
L('NUM_KV_HEADS = 2')
L('NUM_HEADS = 8          # GQA: 8 // 2 = 4 repeats')
L('HEAD_DIM = 32')
L('N_REPEATS = NUM_HEADS // NUM_KV_HEADS')
L('SCALE = HEAD_DIM ** -0.5')
L('')
L('')
L('@pytest.fixture')
L('def pool_tensors():')
L('    """Return a single layer key_cache and value_cache on CPU, fp16."""')
L('    kc = torch.empty(NUM_BLOCKS, NUM_KV_HEADS, BLOCK_SIZE, HEAD_DIM,')
L('                     dtype=torch.float16)')
L('    vc = torch.empty(NUM_BLOCKS, NUM_KV_HEADS, BLOCK_SIZE, HEAD_DIM,')
L('                     dtype=torch.float16)')
L('    return kc, vc')
L('')
L('')
L('def make_kv(num_tokens: int, seed: int = 0,')
L('            num_kv_heads: int = NUM_KV_HEADS,')
L('            head_dim: int = HEAD_DIM) -> tuple:')
L('    """Create random K and V tensors with known values."""')
L('    g = torch.Generator()')
L('    g.manual_seed(seed)')
L('    k = torch.randn(num_tokens, num_kv_heads, head_dim,')
L('                    dtype=torch.float16, generator=g)')
L('    v = torch.randn(num_tokens, num_kv_heads, head_dim,')
L('                    dtype=torch.float16, generator=g)')
L('    return k, v')
L('')
L('')
L('# ---------------------------------------------------------------------------')
L('# SDPA helpers  ([B, H, L, D] layout)')
L('# ---------------------------------------------------------------------------')
L('')
L('')
L('def _sdpa_decode(q, k, v, scale=None):')
L('    """SDPA for decode: Q=1, no mask."""')
L('    qs = q.unsqueeze(2)                   # [1, H, 1, D]')
L('    ks = k.permute(1, 0, 2).unsqueeze(0)  # [1, H, kv_len, D]')
L('    vs = v.permute(1, 0, 2).unsqueeze(0)')
L('    out = F.scaled_dot_product_attention(qs, ks, vs, is_causal=False, scale=scale)')
L('    return out.squeeze(2)  # [1, H, D]')
L('')
L('')
L('def _sdpa_prefill(q, k, v, cached, scale=None):')
L('    """SDPA for prefill with offset-aware causal mask."""')
L('    qs = q.permute(1, 0, 2).unsqueeze(0)       # [1, H, q_len, D]')
L('    ks = k.permute(1, 0, 2).unsqueeze(0)       # [1, H, kv_len, D]')
L('    vs = v.permute(1, 0, 2).unsqueeze(0)')
L('    q_len = q.shape[0]')
L('    kv_len = k.shape[0]')
L('    q_pos = torch.arange(cached, cached + q_len)')
L('    k_pos = torch.arange(kv_len)')
L('    mask = k_pos.unsqueeze(0) <= q_pos.unsqueeze(1)')
L('    out = F.scaled_dot_product_attention(')
L('        qs, ks, vs, attn_mask=mask, is_causal=False, scale=scale,')
L('    )')
L('    return out.squeeze(0).permute(1, 0, 2)  # [q_len, H, D]')
L('')
L('')
L('def _make_decode_meta(seq_indices, cached_len_before, decode_block_tables):')
L('    """Build AttentionMetadata for decode-only step."""')
L('    dec_cached = torch.tensor(cached_len_before, dtype=torch.long)')
L('    dec_query = torch.ones(len(seq_indices), dtype=torch.long)')
L('    group = AttentionGroup(')
L('        seq_indices=seq_indices, attention_type="decode_gpu",')
L('        cached_len_before=dec_cached, query_len=dec_query,')
L('        kv_len_after=dec_cached + dec_query,')
L('    )')
L('    return AttentionMetadata(')
L('        groups=[group],')
L('        decode_block_tables=decode_block_tables,')
L('        block_size=BLOCK_SIZE, num_kv_heads=NUM_KV_HEADS, head_dim=HEAD_DIM,')
L('    )')
L('')
L('')
L('def _make_prefill_meta(seq_indices, cached_len_before, query_len, prefill_block_tables):')
L('    """Build AttentionMetadata for prefill step."""')
L('    pref_cached = torch.tensor(cached_len_before, dtype=torch.long)')
L('    pref_query = torch.tensor(query_len, dtype=torch.long)')
L('    group = AttentionGroup(')
L('        seq_indices=seq_indices, attention_type="prefill_gpu",')
L('        cached_len_before=pref_cached, query_len=pref_query,')
L('        kv_len_after=pref_cached + pref_query,')
L('    )')
L('    return AttentionMetadata(')
L('        groups=[group],')
L('        prefill_block_tables=prefill_block_tables,')
L('        block_size=BLOCK_SIZE, num_kv_heads=NUM_KV_HEADS, head_dim=HEAD_DIM,')
L('    )')
L('')
L('')
L('def _fake_pool(key_cache, value_cache):')
L('    """Create a minimal fake pool object."""')
L('    from dataclasses import dataclass')
L('    @dataclass')
L('    class _FakePool:')
L('        key_caches: list')
L('        value_caches: list')
L('        num_blocks: int')
L('        block_size: int')
L('        num_layers: int')
L('        num_kv_heads: int')
L('        head_dim: int')
L('        device: torch.device')
L('        dtype: torch.dtype')
L('        def get_key_cache(self, i): return self.key_caches[i]')
L('        def get_value_cache(self, i): return self.value_caches[i]')
L('    return _FakePool(')
L('        key_caches=[key_cache], value_caches=[value_cache],')
L('        num_blocks=key_cache.shape[0], block_size=key_cache.shape[2],')
L('        num_layers=1, num_kv_heads=key_cache.shape[1],')
L('        head_dim=key_cache.shape[3], device=key_cache.device,')
L('        dtype=key_cache.dtype,')
L('    )')
L('')
L('')
L('def _paged_backend(kc, vc):')
L('    """Create AttentionBackendRef wired to given cache."""')
L('    backend = AttentionBackendRef(ModelConfig(num_kv_heads=NUM_KV_HEADS))')
L('    backend._pool = _fake_pool(kc, vc)')
L('    backend._block_size = BLOCK_SIZE')
L('    return backend')
L('')
L('')
L('# ===================================================================')
L('# gather_paged_kv tests')
L('# ===================================================================')
L('')
L('')
L('class TestGatherPagedKV:')
L('')
L('    def _write_and_gather(self, kc, vc, num_tokens, seed, slots=None):')
L('        """Write KV and return (k_in, v_in, block_ids)."""')
L('        k_in, v_in = make_kv(num_tokens, seed=seed)')
L('        if slots is None:')
L('            slots = torch.arange(num_tokens, dtype=torch.long)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, slots, BLOCK_SIZE)')
L('        block_start = slots[0].item() // BLOCK_SIZE')
L('        num_blocks = (slots[-1].item() - slots[0].item() + BLOCK_SIZE) // BLOCK_SIZE')
L('        block_ids = list(range(block_start, block_start + num_blocks))')
L('        return k_in, v_in, block_ids')
L('')
L('    def test_gather_full_block(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in, bids = self._write_and_gather(kc, vc, BLOCK_SIZE, 10,')
L('                                                  torch.arange(12, 16, dtype=torch.long))')
L('        k_out, v_out = gather_paged_kv(kc, vc, bids, BLOCK_SIZE, BLOCK_SIZE)')
L('        assert torch.equal(k_out, k_in)')
L('        assert torch.equal(v_out, v_in)')
L('')
L('    def test_gather_partial_block(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in, bids = self._write_and_gather(kc, vc, 3, 11,')
L('                                                  torch.tensor([12, 13, 14], dtype=torch.long))')
L('        k_out, v_out = gather_paged_kv(kc, vc, bids, 3, BLOCK_SIZE)')
L('        assert torch.equal(k_out, k_in)')
L('')
L('    def test_gather_multi_block(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in, bids = self._write_and_gather(kc, vc, 10, 12,')
L('                                                  torch.arange(4, 14, dtype=torch.long))')
L('        k_out, v_out = gather_paged_kv(kc, vc, bids, 10, BLOCK_SIZE)')
L('        assert torch.equal(k_out, k_in)')
L('')
L('    def test_gather_non_contiguous(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in = make_kv(10, 13)')
L('        slots = torch.tensor([28, 29, 30, 31, 12, 13, 14, 15, 60, 61], dtype=torch.long)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, slots, BLOCK_SIZE)')
L('        k_out, v_out = gather_paged_kv(kc, vc, [7, 3, 15], 10, BLOCK_SIZE)')
L('        assert torch.equal(k_out, k_in)')
L('')
L('    def test_gather_zero_tokens(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_out, v_out = gather_paged_kv(kc, vc, [], 0, BLOCK_SIZE)')
L('        assert k_out.shape == (0, NUM_KV_HEADS, HEAD_DIM)')
L('        assert v_out.shape == (0, NUM_KV_HEADS, HEAD_DIM)')
L('')
L('    def test_gather_round_trip(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in, bids = self._write_and_gather(kc, vc, 7, 14,')
L('                                                  torch.arange(4, 11, dtype=torch.long))')
L('        k_out, v_out = gather_paged_kv(kc, vc, bids, 7, BLOCK_SIZE)')
L('        assert torch.equal(k_out, k_in)')
L('')
L('    def test_gather_insufficient(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        with pytest.raises(IndexError, match="insufficient"):')
L('            gather_paged_kv(kc, vc, [0], 8, BLOCK_SIZE)')
L('')
L('')
L('# ===================================================================')
L('# Decode attention tests  (方案 B: write decode token, gather all)')
L('# ===================================================================')
L('')
L('')
L('class TestDecodeAttention:')
L('')
L('    def _setup_decode(self, kc, vc, cached, seed, slot_offset=0):')
L('        """Write cached+1 tokens and return (k_in, v_in, block_ids, kv_len_after)."""')
L('        kv_len_after = cached + 1')
L('        k_in, v_in = make_kv(kv_len_after, seed=seed)')
L('        slots = torch.arange(slot_offset, slot_offset + kv_len_after, dtype=torch.long)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, slots, BLOCK_SIZE)')
L('        block_start = slot_offset // BLOCK_SIZE')
L('        num_blocks = (kv_len_after + BLOCK_SIZE - 1) // BLOCK_SIZE')
L('        block_ids = list(range(block_start, block_start + num_blocks))')
L('        return k_in, v_in, block_ids, kv_len_after')
L('')
L('    def test_decode_single_seq(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in, bids, kv_len = self._setup_decode(kc, vc, 4, 20)')
L('        q = torch.randn(1, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([bids], dtype=torch.long)')
L('        meta = _make_decode_meta([0], [4], bt)')
L('        backend = _paged_backend(kc, vc)')
L('        out = backend.decode_attention(0, q, meta, backend._pool)')
L('        ref = _sdpa_decode(q, k_in.repeat_interleave(N_REPEATS, dim=1),')
L('                            v_in.repeat_interleave(N_REPEATS, dim=1), SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_decode_multi_seq(self, pool_tensors):')
L('        """3 seqs with non-overlapping physical blocks."""')
L('        kc, vc = pool_tensors')
L('        configs = [(4, 20, 0), (8, 21, 16), (12, 22, 32)]')
L('        q_all = torch.randn(3, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        refs = []; block_rows = []')
L('        for idx, (cached, seed, soff) in enumerate(configs):')
L('            k_in, v_in, bids, _ = self._setup_decode(kc, vc, cached, seed, soff)')
L('            block_rows.append(bids + [-1] * (8 - len(bids)))')
L('            refs.append(_sdpa_decode(q_all[idx:idx+1],')
L('                k_in.repeat_interleave(N_REPEATS, dim=1),')
L('                v_in.repeat_interleave(N_REPEATS, dim=1), SCALE))')
L('        bt = torch.tensor(block_rows, dtype=torch.long)')
L('        meta = _make_decode_meta([0, 1, 2], [4, 8, 12], bt)')
L('        out = _paged_backend(kc, vc).decode_attention(0, q_all, meta, _paged_backend(kc, vc)._pool)')
L('        for i in range(3):')
L('            assert torch.allclose(out[i:i+1], refs[i], atol=1e-3), f"seq {i}"')
L('')
L('    def test_decode_block_boundary(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in, bids, _ = self._setup_decode(kc, vc, 7, 40)')
L('        assert bids == [0, 1]')
L('        q = torch.randn(1, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([bids], dtype=torch.long)')
L('        meta = _make_decode_meta([0], [7], bt)')
L('        backend = _paged_backend(kc, vc)')
L('        out = backend.decode_attention(0, q, meta, backend._pool)')
L('        ref = _sdpa_decode(q, k_in.repeat_interleave(N_REPEATS, dim=1),')
L('                            v_in.repeat_interleave(N_REPEATS, dim=1), SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_decode_non_contiguous(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in = make_kv(8, 50)')
L('        slots = torch.cat([torch.arange(28, 32), torch.arange(12, 16)]).to(torch.long)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, slots, BLOCK_SIZE)')
L('        q = torch.randn(1, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([[7, 3]], dtype=torch.long)')
L('        meta = _make_decode_meta([0], [8], bt)')
L('        backend = _paged_backend(kc, vc)')
L('        out = backend.decode_attention(0, q, meta, backend._pool)')
L('        ref = _sdpa_decode(q, k_in.repeat_interleave(N_REPEATS, dim=1),')
L('                            v_in.repeat_interleave(N_REPEATS, dim=1), SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_decode_gqa(self, pool_tensors):')
L('        """GQA: 2 kv_heads -> 8 q_heads via repeat_interleave(4)."""')
L('        kc, vc = pool_tensors')
L('        k_in, v_in = make_kv(6, 60)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, torch.arange(6, dtype=torch.long), BLOCK_SIZE)')
L('        q = torch.randn(1, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([[0, 1]], dtype=torch.long)')
L('        meta = _make_decode_meta([0], [6], bt)')
L('        backend = _paged_backend(kc, vc)')
L('        out = backend.decode_attention(0, q, meta, backend._pool)')
L('        ref = _sdpa_decode(q, k_in.repeat_interleave(N_REPEATS, dim=1),')
L('                            v_in.repeat_interleave(N_REPEATS, dim=1), SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_decode_partial_last_block(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in = make_kv(5, 70)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, torch.arange(5, dtype=torch.long), BLOCK_SIZE)')
L('        q = torch.randn(1, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([[0, 1]], dtype=torch.long)')
L('        meta = _make_decode_meta([0], [5], bt)')
L('        backend = _paged_backend(kc, vc)')
L('        out = backend.decode_attention(0, q, meta, backend._pool)')
L('        ref = _sdpa_decode(q, k_in.repeat_interleave(N_REPEATS, dim=1),')
L('                            v_in.repeat_interleave(N_REPEATS, dim=1), SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_decode_sentinel_not_read(self, pool_tensors):')
L('        """Only kv_len tokens read; block padding not accessed."""')
L('        kc, vc = pool_tensors')
L('        k_in, v_in = make_kv(4, 80)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, torch.arange(4, dtype=torch.long), BLOCK_SIZE)')
L('        q = torch.randn(1, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([[0]], dtype=torch.long)')
L('        meta = _make_decode_meta([0], [4], bt)')
L('        backend = _paged_backend(kc, vc)')
L('        out = backend.decode_attention(0, q, meta, backend._pool)')
L('        ref = _sdpa_decode(q, k_in.repeat_interleave(N_REPEATS, dim=1),')
L('                            v_in.repeat_interleave(N_REPEATS, dim=1), SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('')
L('# ===================================================================')
L('# Prefill attention tests  (offset-aware causal mask, 方案 B)')
L('# ===================================================================')
L('')
L('')
L('class TestPrefillAttention:')
L('')
L('    def _setup_prefill(self, kc, vc, cached, q_len, seed, slot_offset=0):')
L('        total = cached + q_len')
L('        k, v = make_kv(total, seed=seed)')
L('        slots = torch.arange(slot_offset, slot_offset + total, dtype=torch.long)')
L('        write_to_paged_cache(k, v, kc, vc, slots, BLOCK_SIZE)')
L('        block_start = slot_offset // BLOCK_SIZE')
L('        num_blocks = (total + BLOCK_SIZE - 1) // BLOCK_SIZE')
L('        block_ids = list(range(block_start, block_start + num_blocks))')
L('        return k, v, block_ids')
L('')
L('    def test_prefill_full(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_all, v_all, bids = self._setup_prefill(kc, vc, 0, 6, 90)')
L('        q = torch.randn(6, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([bids], dtype=torch.long)')
L('        meta = _make_prefill_meta([0], [0], [6], bt)')
L('        b = _paged_backend(kc, vc)')
L('        out = b.prefill_attention(0, q, None, None, meta, b._pool)')
L('        ref = _sdpa_prefill(q, k_all.repeat_interleave(N_REPEATS, dim=1),')
L('                            v_all.repeat_interleave(N_REPEATS, dim=1), cached=0, scale=SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_prefill_p8_q2(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_all, v_all, bids = self._setup_prefill(kc, vc, 8, 2, 100)')
L('        q = torch.randn(2, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([bids], dtype=torch.long)')
L('        meta = _make_prefill_meta([0], [8], [2], bt)')
L('        b = _paged_backend(kc, vc)')
L('        out = b.prefill_attention(0, q, None, None, meta, b._pool)')
L('        ref = _sdpa_prefill(q, k_all[:10].repeat_interleave(N_REPEATS, dim=1),')
L('                            v_all[:10].repeat_interleave(N_REPEATS, dim=1), cached=8, scale=SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_prefill_p8_q3(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_all, v_all, bids = self._setup_prefill(kc, vc, 8, 3, 110)')
L('        q = torch.randn(3, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([bids], dtype=torch.long)')
L('        meta = _make_prefill_meta([0], [8], [3], bt)')
L('        b = _paged_backend(kc, vc)')
L('        out = b.prefill_attention(0, q, None, None, meta, b._pool)')
L('        ref = _sdpa_prefill(q, k_all[:11].repeat_interleave(N_REPEATS, dim=1),')
L('                            v_all[:11].repeat_interleave(N_REPEATS, dim=1), cached=8, scale=SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_prefill_p8_q1(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_all, v_all, bids = self._setup_prefill(kc, vc, 8, 1, 120)')
L('        q = torch.randn(1, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([bids], dtype=torch.long)')
L('        meta = _make_prefill_meta([0], [8], [1], bt)')
L('        b = _paged_backend(kc, vc)')
L('        out = b.prefill_attention(0, q, None, None, meta, b._pool)')
L('        ref = _sdpa_prefill(q, k_all[:9].repeat_interleave(N_REPEATS, dim=1),')
L('                            v_all[:9].repeat_interleave(N_REPEATS, dim=1), cached=8, scale=SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_prefill_multi_seq(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k0, v0 = make_kv(4, 130)')
L('        write_to_paged_cache(k0, v0, kc, vc, torch.arange(4, dtype=torch.long), BLOCK_SIZE)')
L('        k1, v1 = make_kv(10, 131)')
L('        write_to_paged_cache(k1, v1, kc, vc, torch.arange(16, 26, dtype=torch.long), BLOCK_SIZE)')
L('        q0 = torch.randn(4, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        q1 = torch.randn(2, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        q = torch.cat([q0, q1], dim=0)')
L('        bt = torch.tensor([[0, -1], [4, 5, 6]], dtype=torch.long)')
L('        meta = _make_prefill_meta([0, 1], [0, 8], [4, 2], bt)')
L('        b = _paged_backend(kc, vc)')
L('        out = b.prefill_attention(0, q, None, None, meta, b._pool)')
L('        ref0 = _sdpa_prefill(q0, k0[:4].repeat_interleave(N_REPEATS, dim=1),')
L('                             v0[:4].repeat_interleave(N_REPEATS, dim=1), cached=0, scale=SCALE)')
L('        ref1 = _sdpa_prefill(q1, k1[:10].repeat_interleave(N_REPEATS, dim=1),')
L('                             v1[:10].repeat_interleave(N_REPEATS, dim=1), cached=8, scale=SCALE)')
L('        ref = torch.cat([ref0, ref1], dim=0)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('')
L('# ===================================================================')
L('# Dimension semantic test  (seq_len != num_heads)')
L('# ===================================================================')
L('')
L('')
L('class TestDimensionSemantics:')
L('    """Verify SDPA layout is [B, H, L, D] and not accidentally swapped.')
L('')
L('    Use small HEAD_DIM=4, single kv_head, and seq_len != num_heads to')
L('    catch layout bugs that dimension-agnostic tests might miss.')
L('    """')
L('')
L('    def test_decode_dim_semantics(self):')
L('        """decode: head_dim=4, seq_len=1, num_heads=4 (diff from seq_len)."""')
L('        NH = 4; HD = 4; NBLK = 2; BS = 2')
L('        kc = torch.empty(NBLK, 1, BS, HD, dtype=torch.float16)')
L('        vc = torch.empty(NBLK, 1, BS, HD, dtype=torch.float16)')
L('        k_in, v_in = make_kv(2, 200, num_kv_heads=1, head_dim=HD)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, torch.arange(2, dtype=torch.long), BS)')
L('        q = torch.randn(1, NH, HD, dtype=torch.float16)')
L('        bt = torch.tensor([[0]], dtype=torch.long)')
L('        dec_c = torch.tensor([2], dtype=torch.long)')
L('        dec_q = torch.ones(1, dtype=torch.long)')
L('        grp = AttentionGroup([0], "decode_gpu", dec_c, dec_q, dec_c + dec_q)')
L('        meta = AttentionMetadata([grp], decode_block_tables=bt,')
L('                                 block_size=BS, num_kv_heads=1, head_dim=HD)')
L('        out = _paged_backend(kc, vc).decode_attention(0, q, meta, _paged_backend(kc, vc)._pool)')
L('        assert out.shape == (1, NH, HD), f"decode out shape {out.shape}"')
L('        ref = _sdpa_decode(q, k_in.repeat_interleave(NH, dim=1),')
L('                            v_in.repeat_interleave(NH, dim=1), SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('    def test_prefill_dim_semantics(self):')
L('        """prefill: head_dim=4, seq_len=3, num_heads=4 (diff from seq_len)."""')
L('        NH = 4; HD = 4; NBLK = 4; BS = 4')
L('        kc = torch.empty(NBLK, 1, BS, HD, dtype=torch.float16)')
L('        vc = torch.empty(NBLK, 1, BS, HD, dtype=torch.float16)')
L('        k_all, v_all = make_kv(3, 210, num_kv_heads=1, head_dim=HD)')
L('        write_to_paged_cache(k_all, v_all, kc, vc, torch.arange(3, dtype=torch.long), BS)')
L('        q = torch.randn(3, NH, HD, dtype=torch.float16)')
L('        bt = torch.tensor([[0]], dtype=torch.long)')
L('        pref_c = torch.tensor([0], dtype=torch.long)')
L('        pref_q = torch.tensor([3], dtype=torch.long)')
L('        grp = AttentionGroup([0], "prefill_gpu", pref_c, pref_q, pref_c + pref_q)')
L('        meta = AttentionMetadata([grp], prefill_block_tables=bt,')
L('                                 block_size=BS, num_kv_heads=1, head_dim=HD)')
L('        out = _paged_backend(kc, vc).prefill_attention(0, q, None, None, meta, _paged_backend(kc, vc)._pool)')
L('        assert out.shape == (3, NH, HD), f"prefill out shape {out.shape}"')
L('        ref = _sdpa_prefill(q, k_all.repeat_interleave(NH, dim=1),')
L('                            v_all.repeat_interleave(NH, dim=1), cached=0, scale=HD ** -0.5)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('')
L('# ===================================================================')
L('# Future-token leakage test  (hand-verifiable, single head, small dim)')
L('# ===================================================================')
L('')
L('')
L('class TestFutureTokenLeakage:')
L('    """Hand-verifiable test that q_i cannot attend to k_{>P+i}.')
L('')
L('    Single kv_head, head_dim=4. V is set to distinct values per position.')
L('    Future positions have extreme V. If the causal mask leaks, q0 output')
L('    will change; if correct, only q1/q2 see the new positions.')
L('    """')
L('')
L('    def test_future_tokens_blocked(self):')
L('        NH = 2; HD = 4; BS = 4; NBLK = 4')
L('        kc = torch.empty(NBLK, 1, BS, HD, dtype=torch.float16)')
L('        vc = torch.empty(NBLK, 1, BS, HD, dtype=torch.float16)')
L('        # P=4, Q=3. V at each position is distinct')
L('        k_all = torch.zeros(7, 1, HD, dtype=torch.float16)')
L('        v_all = torch.zeros(7, 1, HD, dtype=torch.float16)')
L('        for pos in range(7):')
L('            v_all[pos, 0, :] = pos + 1  # position-identifying values')
L('            k_all[pos, 0, :] = pos + 1')
L('        # Corrupt future positions (pos >= 5) with extreme V')
L('        v_all[5:, 0, :] = 1e4')
L('        write_to_paged_cache(k_all, v_all, kc, vc, torch.arange(7, dtype=torch.long), BS)')
L('        # q_i at position P+i')
L('        q = torch.randn(3, NH, HD, dtype=torch.float16)')
L('        bt = torch.tensor([[0, 1]], dtype=torch.long)')
L('        pref_c = torch.tensor([4], dtype=torch.long)')
L('        pref_q = torch.tensor([3], dtype=torch.long)')
L('        grp = AttentionGroup([0], "prefill_gpu", pref_c, pref_q, pref_c + pref_q)')
L('        meta = AttentionMetadata([grp], prefill_block_tables=bt,')
L('                                 block_size=BS, num_kv_heads=1, head_dim=HD)')
L('        b = _paged_backend(kc, vc)')
L('        out = b.prefill_attention(0, q, None, None, meta, b._pool)')
L('        # Reference using correct mask (also blocks positions >= 5 for q0)')
L('        k_gqa = k_all.repeat_interleave(NH, dim=1)')
L('        v_gqa = v_all.repeat_interleave(NH, dim=1)')
L('        ref = _sdpa_prefill(q, k_gqa, v_gqa, cached=4, scale=HD ** -0.5)')
L('        assert torch.allclose(out, ref, atol=1e-3), "Future tokens leaked"')
L('        # Additional: q0 should NOT have extreme V in its output')
L('        v_without_corruption = v_all.clone()')
L('        v_without_corruption[5:, 0, :] = torch.arange(5, 8).unsqueeze(1).expand(2, HD).to(torch.float16)')
L('        ref_clean = _sdpa_prefill(q, k_gqa, v_without_corruption.repeat_interleave(NH, dim=1), cached=4, scale=HD ** -0.5)')
L('        # q0 output should be same whether future V is corrupted or clean')
L('        assert torch.allclose(out[0:1], ref_clean[0:1], atol=1e-2), "q0 affected by future V"')
L('        assert not torch.allclose(out[1:2], ref_clean[1:2], atol=1e-1), "q1 should differ (sees pos 5)"')
L('')
L('')
L('# ===================================================================')
L('# Scale tests')
L('# ===================================================================')
L('')
L('')
L('class TestAttentionScale:')
L('    def test_scale_is_one_over_sqrt_head_dim(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_in, v_in = make_kv(4, 150)')
L('        write_to_paged_cache(k_in, v_in, kc, vc, torch.arange(4, dtype=torch.long), BLOCK_SIZE)')
L('        q = torch.randn(1, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([[0]], dtype=torch.long)')
L('        meta = _make_decode_meta([0], [4], bt)')
L('        out = _paged_backend(kc, vc).decode_attention(0, q, meta, _paged_backend(kc, vc)._pool)')
L('        k_gqa = k_in.repeat_interleave(N_REPEATS, dim=1)')
L('        v_gqa = v_in.repeat_interleave(N_REPEATS, dim=1)')
L('        assert torch.allclose(out, _sdpa_decode(q, k_gqa, v_gqa, SCALE), atol=1e-3)')
L('        ref_default = _sdpa_decode(q, k_gqa, v_gqa)')
L('        ref_no_scale = _sdpa_decode(q, k_gqa, v_gqa, scale=1.0)')
L('        diff = torch.max(torch.abs(ref_default - ref_no_scale)).item()')
L('        assert diff > 1e-6, f"Scale 1/sqrt(hd) vs 1.0 diff={diff}"')
L('')
L('')
L('# ===================================================================')
L('# Causal mask alignment tests')
L('# ===================================================================')
L('')
L('')
L('class TestCausalMask:')
L('    def test_causal_mask_hand_crafted(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        k_all, v_all = make_kv(10, 160)')
L('        write_to_paged_cache(k_all, v_all, kc, vc, torch.arange(10, dtype=torch.long), BLOCK_SIZE)')
L('        q = torch.randn(3, NUM_HEADS, HEAD_DIM, dtype=torch.float16)')
L('        bt = torch.tensor([[0, 1, 2]], dtype=torch.long)')
L('        meta = _make_prefill_meta([0], [7], [3], bt)')
L('        b = _paged_backend(kc, vc)')
L('        out = b.prefill_attention(0, q, None, None, meta, b._pool)')
L('        ref = _sdpa_prefill(q, k_all[:10].repeat_interleave(N_REPEATS, dim=1),')
L('                            v_all[:10].repeat_interleave(N_REPEATS, dim=1), cached=7, scale=SCALE)')
L('        assert torch.allclose(out, ref, atol=1e-3)')
L('')
L('')
L('# ===================================================================')
L('# Backend integration tests')
L('# ===================================================================')
L('')
L('')
L('class TestBackendIntegration:')
L('    def test_write_kv_cache(self, pool_tensors):')
L('        kc, vc = pool_tensors')
L('        b = _paged_backend(kc, vc)')
L('        k_in, v_in = make_kv(3, 170)')
L('        b.write_kv_cache(0, k_in, v_in, torch.tensor([4, 5, 6], dtype=torch.long))')
L('        k_out, v_out = gather_paged_kv(kc, vc, [1], 3, BLOCK_SIZE)')
L('        assert torch.equal(k_out, k_in)')
L('        assert torch.equal(v_out, v_in)')
L('')
L('    def test_backend_factory(self):')
L('        config = ModelConfig(num_kv_heads=NUM_KV_HEADS)')
L('        backend = AttentionBackendFactory.create(config, backend="reference")')
L('        assert isinstance(backend, AttentionBackendRef)')
L('')
L('    def test_allocate_pool(self):')
L('        b = AttentionBackendRef(ModelConfig(num_kv_heads=NUM_KV_HEADS))')
L('        pool = b.allocate_pool(2, 8, 4, 2, 32, torch.float16, torch.device("cpu"))')
L('        assert pool.num_blocks == 8')
L('        assert len(pool.key_caches) == 2')
L('        assert pool.key_caches[0].shape == (8, 2, 4, 32)')
L('')
L('')
L('# ===================================================================')
L('# Entry point')
L('# ===================================================================')
L('')
L('')
W()
